# Generated by Django 3.2.3 on 2021-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210701_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
